# Generated by Django 5.2.8 on 2026-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_notification_viewhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "birth_place",
                    models.CharField(max_length=200, verbose_name="Место рождения"),
                ),
                ("biography", models.TextField(verbose_name="Биография")),
                (
                    "photo",
                    models.ImageField(upload_to="actors/", verbose_name="Фотография"),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Рост (см)"
                    ),
                ),
                ("awards", models.TextField(blank=True, verbose_name="Награды")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="film",
            name="actors",
            field=models.ManyToManyField(
                blank=True,
                related_name="films",
                to="films.actor",
                verbose_name="Актеры",
            ),
        ),
    ]
